name: Build

on:
  workflow_call:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-rust:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup cache
        uses: Swatinem/rust-cache@v1

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

        - name: Install cargo-make
          run: cargo install --force cargo-make

        - name: Build rust
          run: cargo make build
